terraform {
  required_version = ">= 1.3.0"
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

locals {
  # Paste ONE project ID per line in this heredoc (no emojis/status cols needed).
  raw = <<EOT
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az6_devops-private-alb
projects_Parents_aws_devops_prod_global_route53-records_hrd-reporting_com_staging_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az6_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_network_vpc-peering-connections_test-reporting
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_tf-devops1-parent-control-plane
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks-distro_kubernetes-csi_external-resizer
projects_Parents_aws_devops_prod_us-east-1_load-balancers_devops-internal
projects_Parents_aws_devops_prod_global_route53-records_hrd-reporting_com_dev_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_ghcr_io_argoproj-labs_argocd-extensions
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks_aws-load-balancer-controller
projects_Parents_aws_devops_prod_global_iam-roles_aws-ebs-csi-driver
prod-data_dev_aws_global_route53-zones_dev_hrd-dse_com
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_ebs-csi-driver_volume-modifier-for-k8s
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_registry_k8s_io_external-dns_external-dns
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az6_devops-public
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_ebs-csi-driver_aws-ebs-csi-driver
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_zabbix_zabbix-agent2
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_quay_io_argoproj_argocd
projects_Parents_aws_devops_prod_us-east-1_load-balancers_vpce-to-devops-alb
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_cr_l5d_io_linkerd_cni-plugin
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az2_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_network_nat-gateways_use1-az4_devops
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az1_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoint-services_devops-monitoring
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks-distro_kubernetes-csi_external-provisioner
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_zabbix_zabbix-server-pgsql
projects_Parents_aws_devops_prod_us-east-1_s3_hrd-devops-pyroscope
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_custom_rsyslog
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_springcloud_spring-cloud-kubernetes-configuration-watcher
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoint-services_devops-alb
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_ghcr_io_external-secrets_external-secrets
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_dev-parent
projects_Parents_aws_devops_prod_us-east-1_network_vpc-peering-connections_Dev-DevOps
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_gcr_io_k8s-staging-test-infra_kubekins-e2e
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_https-allow-from-all
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az4_tf-devops1-parent
prod-data_prod_aws_us-east-1_network_vpcs_eks
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-cloud-api-key
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az4_tf-devops1-parent-pod
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_reporting-staging
projects_Parents_aws_devops_prod_us-east-1_s3_hrd-devops-mimir-tsdb
projects_Parents_aws_devops_prod_us-east-1_karpenter
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az4_devops-public
prod-data_prod_aws_global_route53-zones_prod_hrd-dse_com
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az2_devops-public
projects_Parents_aws_devops_prod_us-east-1_eks_tf-devops1-parent
projects_Parents_aws_devops_prod_global_iam-roles_cloudhealth
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoints_devops-ecr
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az6_tf-devops1-parent
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_reporting-prod
projects_Parents_aws_devops_prod_us-east-1_load-balancers_devops-internal-nlb
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-reg-platform-api
projects_Parents_aws_dev_ops_prod_us-east-1_network_nat-gateways_use1-az6_devops
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_cisco2loki-nlb-az1
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_temp-dev-bedrock-gw
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_curlimages_curl
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-stage-platform-api
projects_Parents_aws_devops_prod_global_iam-roles_atlantis
prod-data_dev_aws_us-east-1_network_vpcs_eks
projects_Parents_aws_devops_prod_us-east-1_network_nat-gateways_use1-az1_devops
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks-distro_kubernetes-csi_livenessprobe
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_allow-ssh-mgmt
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_psql-tooling-01
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_vpce-nlb-devops
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-cloud-api-secret
projects_Parents_aws_devops_prod_us-east-1_network_nat-gateways_use1-az2_devops
projects_Parents_aws_devops_prod_global_iam-roles_external-secrets
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_library_postgres
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_zabbix_zabbix-web-nginx-pgsql
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az6_tf-devops1-parent
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoints_devops-ecr-dkr
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_reporting-reg
projects_Parents_aws_devops_prod_us-east-1_secrets_okta-api-token
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az1_tf-devops1-parent
projects_Parents_aws_devops_prod_global_iam-roles_aws-load-balancer-controller
projects_Parents_aws_devops_prod_us-east-1_secrets_databricks-token
projects_Parents_aws_devops_prod_us-east-1_network_vpcs_devops
projects_Reporting_test_aws_us-east-1_network_vpcs_reporting-old
projects_Parents_aws_devops_prod_global_iam-roles_argocd
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks-distro_kubernetes-csi_external-attacher
projects_Parents_aws_devops_prod_global_iam-roles_falco-audit
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az4_devops-private-alb
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az1_devops-public
projects_Parents_aws_devops_prod_us-east-1_target-groups_devops-alb
projects_Parents_aws_devops_prod_global_route53-records_hrd-reporting_com_test_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_tf-devops1-parent-lb
projects_Parents_aws_devops_prod_global_iam-roles_mimir
projects_Reporting_prod_aws_global_route53-zones_prod_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_secrets_psql-tooling-01
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoint-services_devops-internal
projects_Parents_aws_devops_prod_global_iam-roles_external-dns
projects_Parents_aws_devops_prod_global_ipam_root
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_cisco2loki-nlb-az2
projects_Parents_aws_devops_prod_us-east-1_network_managed-prefix-lists_jira
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_cisco2loki-nlb-az6
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_reporting-test
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_dev-devops
projects_Parents_aws_devops_prod_us-east-1_secrets_zabbix-oktacert
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_busybox
projects_Parents_aws_devops_prod_global_route53-records_hrd-reporting_com_reg_hrd-reporting_com
projects_Parents_aws_devops_prod_global_iam-roles_pyroscope
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_kiosk2loki-nlb-az2
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-test-platform-api
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_reporting-dev
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az4_tf-devops1-parent
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az1_devops-public
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-dev-platform-api
projects_Parents_aws_devops_prod_global_iam-roles_aws-efs-csi-driver
projects_Reporting_reg_aws_global_route53-zones_reg_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_network_vpc-endpoints_devops-s3
projects_Parents_aws_devops_prod_us-east-1_load-balancers_devops-monitoring
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az4_devops-public
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_cisco2loki-nlb-az4
projects_Parents_aws_devops_prod_global_iam-policies_external-secrets
projects_Parents_aws_devops_prod_global_route53-records_hrd-dse_com_prod_hrd-dse_com
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az2_devops-private-alb
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_public_ecr_aws_eks-distro_kubernetes-csi_node-driver-registrar
projects_Parents_aws_devops_prod_us-east-1_target-groups_devops-monitoring
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az2_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_secrets_zabbix-zabbixdb
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_devops
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az4_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_grafana_promtail
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_restic_restic
projects_Parents_aws_devops_prod_global_iam-policies_AWSLoadBalancerControllerIAMPolicy
projects_Parents_aws_devops_prod_us-east-1_s3_hrd-devops-mimir-ruler
projects_Parents_aws_dev_dev_us-east-1_endpoints_devops-internal
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az2_devops-public
projects_Reporting_staging_aws_global_route53-zones_staging_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az2_tf-devops1-parent
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_devops-monitoring
projects_Infrastructure_shared_aws_devops_prod_us-east-1_ipam_prod-data
projects_Parents_aws_devops_prod_global_route53-zones_devops_hrd-dev_com
projects_Parents_aws_devops_prod_us-east-1_ecr-repositories_docker_io_zabbix_zabbix-web-service
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_kiosk2loki-nlb-az4
projects_Parents_aws_devops_prod_us-east-1_secrets_confluent-prod-platform-api
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az6_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az1_devops-private-alb
projects_Parents_aws_devops_prod_global_route53-zones_hrd-dse_com
projects_Parents_aws_devops_prod_us-east-1_target-groups_devops-internal-nlb
projects_Parents_aws_devops_prod_global_route53-zones_hrd-reporting_com
projects_Parents_aws_devops_prod_us-east-1_secrets_argocd-oktasecret
projects_Parents_aws_devops_prod_us-east-1_network_ip-addresses_kiosk2loki-nlb-az6
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az1_tf-devops1-parent-pod
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az2_tf-devops1-parent
projects_Parents_aws_devops_prod_us-east-1_secrets_argocd-githubapp
projects_Parents_aws_devops_prod_us-east-1_network_security-groups_devops-internal-nlb
projects_Parents_aws_devops_prod_us-east-1_rds_psql-tooling-01
projects_Parents_aws_devops_prod_global_route53-records_hrd-dse_com_dev_hrd-dse_com
projects_Parents_aws_devops_prod_us-east-1_network_routing-tables_use1-az6_devops-public
projects_Parents_aws_devops_prod_us-east-1_network_subnets_use1-az1_tf-devops1-parent
projects_Parents_aws_devops_prod_global_route53-records_hrd-reporting_com_prod_hrd-reporting_com
projects_Reporting_dev_aws_global_route53-zones_dev_hrd-reporting_com
EOT

  # Split into non-empty lines
  lines = compact(split("\n", trimspace(local.raw)))

  # Build a map of safe Terraform keys -> original names
  # sanitize: spaces, '/', '-', '.', ':' -> '_'
  items = {
    for idx, name in local.lines :
    format("r%04d_%s",
      idx,
      replace(
        replace(
          replace(
            replace(
              replace(name, " ", "_"),
            "/", "_"),
          "-", "_"),
        ".", "_"),
      ":", "_")
    ) => name
  }
}

resource "null_resource" "test" {
  for_each = local.items

  # Keep the original string visible in state
  triggers = {
    original = each.value
  }
}

output "count_created" {
  value = length(local.items)
}

output "example_names" {
  value = slice(keys(local.items), 0, min(5, length(local.items)))
}

