name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        required: true
      run_name:
        required: false

run-name: '${{ inputs.run_name }}'

jobs:
  digger-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: read
      statuses: write
      # id-token is only needed for AWS OIDC; safe to remove for null_resource-only
      # id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Print job id
        run: echo "job id "

      - uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ inputs.spec }}
          setup-terraform: true
          setup-aws: false          # 🚫 turn off AWS setup
          # (no aws-access-key-id / aws-secret-access-key)
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
